org: luizcalaca
app: ingest-data-lambda-service
service: aws-node-express-api-project
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${file(config.json):S3_BUCKET_NAME}/*"

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"
